### ISSUE TITLE
Failed at the apk-parser2@0.1.1 install script 'node install.js'

### ISSUE THREAD

**Issue by tspoke** [gergelyke/node-apk-parser2#2]
Hi,

Trying to npm install your module but it doesn't install itself successfully.
It work perfectly on MacOS but on Windows I can't get it to work :/

I tried with cmd.exe and gitbash, same error on both commands lines.

It gives me this error : 

```
$ npm install app-bundle-info

> apk-parser2@0.1.1 install H:\Projects\Javascript\aze-api\node_modules\apk-parser2
> node install.js

H:\Projects\Javascript\aze-api\node_modules\apk-parser2\install.js:19
    throw new Error('Unknown OS!');
    ^

Error: Unknown OS!
    at Object.<anonymous> (H:\Projects\Javascript\aze-api\node_modules\apk-parser2\install.js:19:11)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3
aze@1.0.0 H:\Projects\Javascript\aze-api
`-- (empty)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "app-bundle-info"
npm ERR! node v5.8.0
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE

npm ERR! apk-parser2@0.1.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the apk-parser2@0.1.1 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the apk-parser2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs apk-parser2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls apk-parser2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     H:\Projects\Javascript\aze-api\npm-debug.log
npm ERR! code 1
```

**Comment by tspoke** [comment]
Sorry, didn't see it :)

#1
